name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs hourly for continuous automation

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}
          submodules: false  # 🚫 Prevents submodule issues

      - name: Pull Latest Changes to Prevent Conflicts
        run: |
          git pull origin main --rebase || echo "No new changes to pull"

      - name: Build Project Files
        run: |
          mkdir -p project_files
          echo "✅ Project built successfully on $(date)" > project_files/BUILD_LOG.txt
          echo "Test file generated." > project_files/test_file.txt

      - name: Commit and Push Project Files
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add project_files
          git commit -m "🚀 Automated build & file upload" || echo "No changes to commit"
          git pull origin main --rebase
          git push https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git main --force
